package edu.buaa.sem.po;
// Generated 2018-5-3 0:05:02 by Hibernate Tools 4.3.1.Final

/**
 * InfParkinglot generated by hbm2java
 */
public class InfParkinglot implements java.io.Serializable {

	private Long id;
	private String number;
	private String name;
	private String address;
	private String classification;
	private Integer spaceTotalAmount;
	private Integer spaceReserveAmount;
	private String account;
	private String key;
	private String description;

	public InfParkinglot() {
	}

	public InfParkinglot(String number, String name, String address, String classification, Integer spaceTotalAmount,
			Integer spaceReserveAmount, String account, String key, String description) {
		this.number = number;
		this.name = name;
		this.address = address;
		this.classification = classification;
		this.spaceTotalAmount = spaceTotalAmount;
		this.spaceReserveAmount = spaceReserveAmount;
		this.account = account;
		this.key = key;
		this.description = description;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getClassification() {
		return this.classification;
	}

	public void setClassification(String classification) {
		this.classification = classification;
	}

	public Integer getSpaceTotalAmount() {
		return this.spaceTotalAmount;
	}

	public void setSpaceTotalAmount(Integer spaceTotalAmount) {
		this.spaceTotalAmount = spaceTotalAmount;
	}

	public Integer getSpaceReserveAmount() {
		return this.spaceReserveAmount;
	}

	public void setSpaceReserveAmount(Integer spaceReserveAmount) {
		this.spaceReserveAmount = spaceReserveAmount;
	}

	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
