package edu.buaa.sem.po;
// Generated 2018-5-2 23:58:39 by Hibernate Tools 4.3.1.Final

/**
 * SysAuthorityResource generated by hbm2java
 */
public class SysAuthorityResource implements java.io.Serializable {

	private Long id;
	private Long sysAuthorityId;
	private Long sysResourceId;
	private String enabled;
	private String type;

	public SysAuthorityResource() {
	}

	public SysAuthorityResource(Long sysAuthorityId, Long sysResourceId, String enabled, String type) {
		this.sysAuthorityId = sysAuthorityId;
		this.sysResourceId = sysResourceId;
		this.enabled = enabled;
		this.type = type;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getSysAuthorityId() {
		return this.sysAuthorityId;
	}

	public void setSysAuthorityId(Long sysAuthorityId) {
		this.sysAuthorityId = sysAuthorityId;
	}

	public Long getSysResourceId() {
		return this.sysResourceId;
	}

	public void setSysResourceId(Long sysResourceId) {
		this.sysResourceId = sysResourceId;
	}

	public String getEnabled() {
		return this.enabled;
	}

	public void setEnabled(String enabled) {
		this.enabled = enabled;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
