package edu.buaa.sem.po;
// Generated 2018-5-3 0:28:09 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * SysEmailModel generated by hbm2java
 */
public class SysEmailModel implements java.io.Serializable {

	private Long id;
	private String emailModelName;
	private String emailModelSubject;
	private String emailModelContent;
	private Date emailModelTime;
	private String emailModelDescription;

	public SysEmailModel() {
	}

	public SysEmailModel(String emailModelName, String emailModelSubject, String emailModelContent, Date emailModelTime,
			String emailModelDescription) {
		this.emailModelName = emailModelName;
		this.emailModelSubject = emailModelSubject;
		this.emailModelContent = emailModelContent;
		this.emailModelTime = emailModelTime;
		this.emailModelDescription = emailModelDescription;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getEmailModelName() {
		return this.emailModelName;
	}

	public void setEmailModelName(String emailModelName) {
		this.emailModelName = emailModelName;
	}

	public String getEmailModelSubject() {
		return this.emailModelSubject;
	}

	public void setEmailModelSubject(String emailModelSubject) {
		this.emailModelSubject = emailModelSubject;
	}

	public String getEmailModelContent() {
		return this.emailModelContent;
	}

	public void setEmailModelContent(String emailModelContent) {
		this.emailModelContent = emailModelContent;
	}

	public Date getEmailModelTime() {
		return this.emailModelTime;
	}

	public void setEmailModelTime(Date emailModelTime) {
		this.emailModelTime = emailModelTime;
	}

	public String getEmailModelDescription() {
		return this.emailModelDescription;
	}

	public void setEmailModelDescription(String emailModelDescription) {
		this.emailModelDescription = emailModelDescription;
	}

}
