package edu.buaa.sem.po;
// Generated 2018-5-2 23:58:39 by Hibernate Tools 4.3.1.Final

/**
 * SysResource generated by hbm2java
 */
public class SysResource implements java.io.Serializable {

	private Long id;
	private String name;
	private String description;
	private String type;
	private String address;
	private String enabled;

	public SysResource() {
	}

	public SysResource(String name, String description, String type, String address, String enabled) {
		this.name = name;
		this.description = description;
		this.type = type;
		this.address = address;
		this.enabled = enabled;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getEnabled() {
		return this.enabled;
	}

	public void setEnabled(String enabled) {
		this.enabled = enabled;
	}

}
