package edu.buaa.sem.po;
// Generated 2018-5-2 23:58:39 by Hibernate Tools 4.3.1.Final

/**
 * SysRoleAuthority generated by hbm2java
 */
public class SysRoleAuthority implements java.io.Serializable {

	private Long id;
	private Long sysRoleId;
	private Long sysAuthorityId;
	private String enabled;

	public SysRoleAuthority() {
	}

	public SysRoleAuthority(Long sysRoleId, Long sysAuthorityId, String enabled) {
		this.sysRoleId = sysRoleId;
		this.sysAuthorityId = sysAuthorityId;
		this.enabled = enabled;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getSysRoleId() {
		return this.sysRoleId;
	}

	public void setSysRoleId(Long sysRoleId) {
		this.sysRoleId = sysRoleId;
	}

	public Long getSysAuthorityId() {
		return this.sysAuthorityId;
	}

	public void setSysAuthorityId(Long sysAuthorityId) {
		this.sysAuthorityId = sysAuthorityId;
	}

	public String getEnabled() {
		return this.enabled;
	}

	public void setEnabled(String enabled) {
		this.enabled = enabled;
	}

}
