package edu.buaa.sem.po;
// Generated 2018-5-2 23:58:39 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * SysUser generated by hbm2java
 */
public class SysUser implements java.io.Serializable {

	private Long id;
	private String name;
	private String password;
	private String description;
	private String enabled;
	private String email;
	private Date creatTime;
	private String headImageUrl;
	private String userType;
	private String selfIntroduction;
	private String ip;
	private String checkStatus;
	private String oauthType;
	private String oauthId;
	private String emailConfirmed;
	private Date lastLoginTime;
	private String emailCode;
	private Date emailTime;
	private String emailHash;
	private Integer maxLogin;
	private String loginIp;
	private Long staffRelate;

	public SysUser() {
	}

	public SysUser(String name, String password, String description, String enabled, String email, Date creatTime,
			String headImageUrl, String userType, String selfIntroduction, String ip, String checkStatus,
			String oauthType, String oauthId, String emailConfirmed, Date lastLoginTime, String emailCode,
			Date emailTime, String emailHash, Integer maxLogin, String loginIp, Long staffRelate) {
		this.name = name;
		this.password = password;
		this.description = description;
		this.enabled = enabled;
		this.email = email;
		this.creatTime = creatTime;
		this.headImageUrl = headImageUrl;
		this.userType = userType;
		this.selfIntroduction = selfIntroduction;
		this.ip = ip;
		this.checkStatus = checkStatus;
		this.oauthType = oauthType;
		this.oauthId = oauthId;
		this.emailConfirmed = emailConfirmed;
		this.lastLoginTime = lastLoginTime;
		this.emailCode = emailCode;
		this.emailTime = emailTime;
		this.emailHash = emailHash;
		this.maxLogin = maxLogin;
		this.loginIp = loginIp;
		this.staffRelate = staffRelate;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getEnabled() {
		return this.enabled;
	}

	public void setEnabled(String enabled) {
		this.enabled = enabled;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Date getCreatTime() {
		return this.creatTime;
	}

	public void setCreatTime(Date creatTime) {
		this.creatTime = creatTime;
	}

	public String getHeadImageUrl() {
		return this.headImageUrl;
	}

	public void setHeadImageUrl(String headImageUrl) {
		this.headImageUrl = headImageUrl;
	}

	public String getUserType() {
		return this.userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	public String getSelfIntroduction() {
		return this.selfIntroduction;
	}

	public void setSelfIntroduction(String selfIntroduction) {
		this.selfIntroduction = selfIntroduction;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public String getCheckStatus() {
		return this.checkStatus;
	}

	public void setCheckStatus(String checkStatus) {
		this.checkStatus = checkStatus;
	}

	public String getOauthType() {
		return this.oauthType;
	}

	public void setOauthType(String oauthType) {
		this.oauthType = oauthType;
	}

	public String getOauthId() {
		return this.oauthId;
	}

	public void setOauthId(String oauthId) {
		this.oauthId = oauthId;
	}

	public String getEmailConfirmed() {
		return this.emailConfirmed;
	}

	public void setEmailConfirmed(String emailConfirmed) {
		this.emailConfirmed = emailConfirmed;
	}

	public Date getLastLoginTime() {
		return this.lastLoginTime;
	}

	public void setLastLoginTime(Date lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}

	public String getEmailCode() {
		return this.emailCode;
	}

	public void setEmailCode(String emailCode) {
		this.emailCode = emailCode;
	}

	public Date getEmailTime() {
		return this.emailTime;
	}

	public void setEmailTime(Date emailTime) {
		this.emailTime = emailTime;
	}

	public String getEmailHash() {
		return this.emailHash;
	}

	public void setEmailHash(String emailHash) {
		this.emailHash = emailHash;
	}

	public Integer getMaxLogin() {
		return this.maxLogin;
	}

	public void setMaxLogin(Integer maxLogin) {
		this.maxLogin = maxLogin;
	}

	public String getLoginIp() {
		return this.loginIp;
	}

	public void setLoginIp(String loginIp) {
		this.loginIp = loginIp;
	}

	public Long getStaffRelate() {
		return this.staffRelate;
	}

	public void setStaffRelate(Long staffRelate) {
		this.staffRelate = staffRelate;
	}

}
