package edu.buaa.sem.po;
// Generated 2018-5-2 23:58:39 by Hibernate Tools 4.3.1.Final

/**
 * SysUserRole generated by hbm2java
 */
public class SysUserRole implements java.io.Serializable {

	private Long id;
	private Long sysUserId;
	private Long sysRoleId;
	private String enabled;

	public SysUserRole() {
	}

	public SysUserRole(Long sysUserId, Long sysRoleId, String enabled) {
		this.sysUserId = sysUserId;
		this.sysRoleId = sysRoleId;
		this.enabled = enabled;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getSysUserId() {
		return this.sysUserId;
	}

	public void setSysUserId(Long sysUserId) {
		this.sysUserId = sysUserId;
	}

	public Long getSysRoleId() {
		return this.sysRoleId;
	}

	public void setSysRoleId(Long sysRoleId) {
		this.sysRoleId = sysRoleId;
	}

	public String getEnabled() {
		return this.enabled;
	}

	public void setEnabled(String enabled) {
		this.enabled = enabled;
	}

}
