package edu.buaa.sem.po;
// Generated 2018-5-2 23:58:39 by Hibernate Tools 4.3.1.Final

/**
 * TraCreditRecord generated by hbm2java
 */
public class TraCreditRecord implements java.io.Serializable {

	private Long id;
	private String orderNumber;
	private Integer amount;
	private String reason;
	private String hash;
	private String descripstion;

	public TraCreditRecord() {
	}

	public TraCreditRecord(Long id) {
		this.id = id;
	}

	public TraCreditRecord(Long id, String orderNumber, Integer amount, String reason, String hash,
			String descripstion) {
		this.id = id;
		this.orderNumber = orderNumber;
		this.amount = amount;
		this.reason = reason;
		this.hash = hash;
		this.descripstion = descripstion;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getOrderNumber() {
		return this.orderNumber;
	}

	public void setOrderNumber(String orderNumber) {
		this.orderNumber = orderNumber;
	}

	public Integer getAmount() {
		return this.amount;
	}

	public void setAmount(Integer amount) {
		this.amount = amount;
	}

	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	public String getHash() {
		return this.hash;
	}

	public void setHash(String hash) {
		this.hash = hash;
	}

	public String getDescripstion() {
		return this.descripstion;
	}

	public void setDescripstion(String descripstion) {
		this.descripstion = descripstion;
	}

}
