package edu.buaa.sem.po;
// Generated 2018-5-2 23:58:39 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * TraOrder generated by hbm2java
 */
public class TraOrder implements java.io.Serializable {

	private Long id;
	private String number;
	private Date createTime;
	private Date reserveBeginPoint;
	private Date reserveEndPoint;
	private String parkinglotNumber;
	private String spaceNumber;
	private String userNumber;
	private String carNumber;
	private String state;
	private Double money;
	private Date inTime;
	private Date outTime;
	private Double debt;
	private String description;

	public TraOrder() {
	}

	public TraOrder(String number, Date createTime, Date reserveBeginPoint, Date reserveEndPoint,
			String parkinglotNumber, String spaceNumber, String userNumber, String carNumber, String state,
			Double money, Date inTime, Date outTime, Double debt, String description) {
		this.number = number;
		this.createTime = createTime;
		this.reserveBeginPoint = reserveBeginPoint;
		this.reserveEndPoint = reserveEndPoint;
		this.parkinglotNumber = parkinglotNumber;
		this.spaceNumber = spaceNumber;
		this.userNumber = userNumber;
		this.carNumber = carNumber;
		this.state = state;
		this.money = money;
		this.inTime = inTime;
		this.outTime = outTime;
		this.debt = debt;
		this.description = description;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getReserveBeginPoint() {
		return this.reserveBeginPoint;
	}

	public void setReserveBeginPoint(Date reserveBeginPoint) {
		this.reserveBeginPoint = reserveBeginPoint;
	}

	public Date getReserveEndPoint() {
		return this.reserveEndPoint;
	}

	public void setReserveEndPoint(Date reserveEndPoint) {
		this.reserveEndPoint = reserveEndPoint;
	}

	public String getParkinglotNumber() {
		return this.parkinglotNumber;
	}

	public void setParkinglotNumber(String parkinglotNumber) {
		this.parkinglotNumber = parkinglotNumber;
	}

	public String getSpaceNumber() {
		return this.spaceNumber;
	}

	public void setSpaceNumber(String spaceNumber) {
		this.spaceNumber = spaceNumber;
	}

	public String getUserNumber() {
		return this.userNumber;
	}

	public void setUserNumber(String userNumber) {
		this.userNumber = userNumber;
	}

	public String getCarNumber() {
		return this.carNumber;
	}

	public void setCarNumber(String carNumber) {
		this.carNumber = carNumber;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public Double getMoney() {
		return this.money;
	}

	public void setMoney(Double money) {
		this.money = money;
	}

	public Date getInTime() {
		return this.inTime;
	}

	public void setInTime(Date inTime) {
		this.inTime = inTime;
	}

	public Date getOutTime() {
		return this.outTime;
	}

	public void setOutTime(Date outTime) {
		this.outTime = outTime;
	}

	public Double getDebt() {
		return this.debt;
	}

	public void setDebt(Double debt) {
		this.debt = debt;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
